In [1]:
import numpy as np
from scipy.linalg import pascal, inv


In [3]:
S = pascal(4, kind='symmetric')

S

array([[ 1,  1,  1,  1],
       [ 1,  2,  3,  4],
       [ 1,  3,  6, 10],
       [ 1,  4, 10, 20]], dtype=uint64)

In [4]:
A = np.abs(pascal(4, kind='lower'))

A

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 2, 1, 0],
       [1, 3, 3, 1]], dtype=uint64)

In [6]:
# inverse of S 
invS = inv(S)

invS

array([[  4.,  -6.,   4.,  -1.],
       [ -6.,  14., -11.,   3.],
       [  4., -11.,  10.,  -3.],
       [ -1.,   3.,  -3.,   1.]])

In [8]:
# to check
invS_test = inv(A.T) @ inv(A)

invS_test

array([[  4.,  -6.,   4.,  -1.],
       [ -6.,  14., -11.,   3.],
       [  4., -11.,  10.,  -3.],
       [ -1.,   3.,  -3.,   1.]])

In [12]:
# they are similar. But also we can test it - 

equal = np.allclose(invS, invS_test, atol=1e-10)
print("Are the two inverses approximately equal?", equal)

# Print the norm of the difference
print("Norm of the difference:", np.linalg.norm(invS - invS_test))# very close to 0

Are the two inverses approximately equal? True
Norm of the difference: 1.5937791926147293e-14
