In [1]:
import numpy as np
from numpy.linalg import lstsq, norm

In [3]:
# 1. A is a rank-deficient matrix (all ones)
A = np.ones((4, 4))
print(A)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# Case 1: b = random
b_rand = np.random.rand(4, 1)
print(b_rand)

[[0.56277575]
 [0.35429844]
 [0.28505612]
 [0.37564934]]


In [5]:
x_rand, residuals_rand, rank_rand, s_rand = lstsq(A, b_rand, rcond=None)
print("Case 1: b = rand(4,1)")
print("x (least squares solution):\n", x_rand)
print("Residual ||Ax - b||:", norm(A @ x_rand - b_rand))
print("Rank of A:", rank_rand)
print()

Case 1: b = rand(4,1)
x (least squares solution):
 [[0.09861123]
 [0.09861123]
 [0.09861123]
 [0.09861123]]
Residual ||Ax - b||: 0.2055874313757611
Rank of A: 1



In [7]:
b_ones = np.ones((4, 1))

# Solve Ax = b
x_ones, residuals_ones, rank_ones, s_ones = lstsq(A, b_ones, rcond=None)
print("Case 2: b = ones(4,1)")
print("x (minimum-norm solution):\n", x_ones)
print("Residual ||Ax - b||:", norm(A @ x_ones - b_ones)) # very close to 0

Case 2: b = ones(4,1)
x (minimum-norm solution):
 [[0.25]
 [0.25]
 [0.25]
 [0.25]]
Residual ||Ax - b||: 1.3322676295501878e-15
