In [1]:
import numpy as np

# Define the matrix
I = np.eye(4)
ones = np.ones((4, 4))
A = 5 * I - ones

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)
print("\nInverse of A:")
print(A_inv)


Matrix A:
[[ 4. -1. -1. -1.]
 [-1.  4. -1. -1.]
 [-1. -1.  4. -1.]
 [-1. -1. -1.  4.]]

Inverse of A:
[[0.4 0.2 0.2 0.2]
 [0.2 0.4 0.2 0.2]
 [0.2 0.2 0.4 0.2]
 [0.2 0.2 0.2 0.4]]


In [2]:
I = np.eye(5)
ones = np.ones((5, 5))
A = 6 * I - ones

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)
print("\nInverse of A:")
print(A_inv)

Matrix A:
[[ 5. -1. -1. -1. -1.]
 [-1.  5. -1. -1. -1.]
 [-1. -1.  5. -1. -1.]
 [-1. -1. -1.  5. -1.]
 [-1. -1. -1. -1.  5.]]

Inverse of A:
[[0.33333333 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.33333333 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.33333333 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.33333333 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.33333333]]
